#!/usr/bin/env bash
# =============================================================================
# deploy-status.sh — Gera e publica o status.html estático no GitHub Pages
#
# Fluxo:
#   1. git pull (garante base limpa)
#   2. Executa generate-status.py (proba os peers via localhost)
#   3. git add docs/status.html
#   4. git commit com timestamp
#   5. git push
#
# Uso:
#   bash /dados/kcp/infra/deploy-status.sh
#
# Cron (a cada 5 minutos):
#   */5 * * * * /dados/kcp/infra/deploy-status.sh >> /var/log/kcp-status-deploy.log 2>&1
# =============================================================================

set -euo pipefail

REPO="/dados/kcp"
PYTHON="/dados/kcp/sdk/python/.venv/bin/python"
SCRIPT="/dados/kcp/infra/generate-status.py"
LOG_PREFIX="[$(date -u '+%Y-%m-%d %H:%M:%S UTC')]"

cd "$REPO"

echo "$LOG_PREFIX === deploy-status start ==="

# 1. Pull latest (stash status.html gerado anteriormente se necessário)
echo "$LOG_PREFIX git pull..."
git stash --quiet 2>/dev/null || true
git pull --quiet --rebase origin main 2>&1 || {
  echo "$LOG_PREFIX WARNING: git pull falhou, continuando com estado local"
}
git stash pop --quiet 2>/dev/null || true

# 2. Gerar o HTML estático
echo "$LOG_PREFIX Gerando status.html..."
$PYTHON "$SCRIPT"

# 3. Verificar se houve mudança real no HTML
if git diff --quiet docs/status.html; then
  echo "$LOG_PREFIX Nenhuma mudança no status.html — skip commit"
  exit 0
fi

# 4. Commit + push
TS=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
echo "$LOG_PREFIX Commitando e publicando..."

git add docs/status.html
git commit -m "chore(status): auto-update network status page [${TS}]

Generated by infra/generate-status.py on VPS.
Peers probed via localhost — no external DNS dependency."

git push origin main

echo "$LOG_PREFIX === deploy-status done ==="
